const menuToggle = document.querySelector('.menu-toggle');
const navLinks = document.querySelector('.nav-links');
menuToggle?.addEventListener('click', () => {
  const open = navLinks.classList.toggle('is-open');
  menuToggle.setAttribute('aria-expanded', String(open));
});
document.querySelectorAll('.nav-links a').forEach((link) => link.addEventListener('click', () => {
  navLinks.classList.remove('is-open');
  menuToggle?.setAttribute('aria-expanded', 'false');
}));
document.getElementById('year').textContent = new Date().getFullYear();

if (document.querySelector('.products-grid')) {
  const style = document.createElement('style'); style.textContent = '.kit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:55px}.kit-card{padding:28px;background:var(--surface);border:1px solid var(--line);border-radius:8px}.kit-card--featured{background:linear-gradient(145deg,#114b65,#0d2338);border-color:rgba(24,231,244,.4)}.kit-index{color:var(--cyan);font-size:10px;letter-spacing:2px}.kit-card h3{font-size:24px;margin:30px 0 10px}.kit-card p{color:var(--muted);font-size:13px;min-height:42px;margin:0 0 18px}.kit-card a{color:var(--cyan);font-size:11px;font-weight:700;text-decoration:none}@media(max-width:800px){.kit-grid{grid-template-columns:1fr}}'; document.head.appendChild(style);
  const filters = document.querySelector('.filter-list');
  [['energia','Energia'],['automacao','Automação'],['gamer','Gamer e home office'],['servicos','Serviços']].forEach(([value,label]) => { const button=document.createElement('button'); button.className='filter-btn'; button.dataset.filter=value; button.textContent=label; filters.appendChild(button); });
  const wa='https://wa.me/5592991587858?text=';
  [['energia','⌁','Nobreaks e proteção','Proteja computadores, roteadores, CFTV e equipamentos contra quedas e oscilações de energia.','Nobreaks|Filtros de linha|Baterias','Consultar opções','Quero consultar nobreaks e proteção de energia.'],['automacao','▤','Automação comercial','Equipamentos para lojas, mercados, farmácias e pequenos negócios: PDV, impressão e controle.','Leitor de código|Impressora térmica','Montar solução','Quero uma solução de automação comercial.'],['gamer','✦','Gamer e home office','Monitores, placas de vídeo, periféricos, webcams e acessórios para jogar ou trabalhar melhor.','PCs gamers|Monitores|Headsets','Montar meu setup','Quero montar um setup gamer ou home office.'],['servicos','&lt;/&gt;','Serviços técnicos','Montagem, instalação de SSD e memória, formatação, migração de dados, configuração e manutenção.','Residencial|Empresarial','Solicitar atendimento','Quero solicitar um serviço técnico.']].forEach(([category,symbol,title,description,meta,action,message]) => { const card=document.createElement('article'); card.className='product-card'; card.dataset.category=category; card.innerHTML=`<div class="product-visual"><span class="product-symbol">${symbol}</span></div><h3>${title}</h3><p>${description}</p><div class="product-meta">${meta.split('|').map(item=>`<span>${item}</span>`).join('')}</div><a class="product-cta" href="${wa}${encodeURIComponent(message)}" target="_blank" rel="noopener">${action} ↗</a>`; document.querySelector('.products-grid').appendChild(card); });
  const kits=document.createElement('div'); kits.className='kit-grid'; kits.innerHTML=[['KIT 01','Home Office','Computador, monitor, teclado, mouse, webcam e nobreak.','Kit Home Office'],['KIT 02','Empresa','Computadores, impressora, rede, nobreak e suporte técnico.','Kit Empresa'],['KIT 03','Segurança','Câmeras, gravador, HD, cabos e instalação de CFTV.','Kit Segurança']].map(([index,title,text,message],i)=>`<article class="kit-card ${i===1?'kit-card--featured':''}"><span class="kit-index">${index}</span><h3>${title}</h3><p>${text}</p><a href="${wa}${encodeURIComponent('Quero montar um '+message+'.')}" target="_blank" rel="noopener">Montar kit ↗</a></article>`).join(''); document.querySelector('.complete-kit').before(kits);
  document.querySelectorAll('.filter-btn').forEach(button=>button.addEventListener('click',()=>{ document.querySelectorAll('.filter-btn').forEach(item=>item.classList.remove('is-active')); button.classList.add('is-active'); const filter=button.dataset.filter; document.querySelectorAll('.product-card').forEach(card=>card.classList.toggle('is-hidden',filter!=='todos'&&card.dataset.category!==filter)); }));
}
