const menuToggle = document.querySelector('.menu-toggle');
const navLinks = document.querySelector('.nav-links');
menuToggle?.addEventListener('click', () => {
  const open = navLinks.classList.toggle('is-open');
  menuToggle.setAttribute('aria-expanded', String(open));
});
document.querySelectorAll('.nav-links a').forEach((link) => link.addEventListener('click', () => {
  navLinks.classList.remove('is-open');
  menuToggle?.setAttribute('aria-expanded', 'false');
}));
document.getElementById('year').textContent = new Date().getFullYear();

document.querySelectorAll('.nav-links').forEach((nav) => {
  if (!nav.querySelector('a[href="produtos-digitais.html"]')) {
    const digitalLink = document.createElement('a');
    digitalLink.href = 'produtos-digitais.html';
    digitalLink.textContent = 'Digitais';
    nav.appendChild(digitalLink);
  }
});

if (document.querySelector('.digital-hero') && !document.querySelector('.campaign-section')) {
  const checkout = 'https://pay.kiwify.com.br/ey4EZjF';
  const section = document.createElement('section'); section.className = 'campaign-section section-pad';
  section.innerHTML = `<div class="container"><div class="section-heading"><div><p class="eyebrow">Kits prontos para suas campanhas</p><h2>Comunicação que <span>gera conexão.</span></h2></div><p>Artes digitais prontas para empresas, lojas, profissionais e redes sociais. Escolha seu kit e veja tudo o que ele inclui.</p></div><div class="campaign-grid"><article class="campaign-card campaign-card--yellow"><div class="campaign-art"><img src="assets/kit-setembro-amarelo.png" alt="Prévia das artes do Kit Setembro Amarelo"></div><div class="campaign-content"><span class="campaign-month">KIT DIGITAL · SETEMBRO</span><h3>Setembro Amarelo</h3><p>50 artes para conscientização e valorização da vida.</p><a href="kit-setembro-amarelo.html">Ver o kit completo <span>↗</span></a></div></article><article class="campaign-card campaign-card--pink campaign-card--featured"><div class="campaign-art"><img src="assets/campanha-outubro-rosa-50-artes-a4.png" alt="Prévia das 50 artes A4 do Kit Outubro Rosa"></div><div class="campaign-content"><span class="campaign-month">KIT DIGITAL · OUTUBRO</span><h3>Outubro Rosa</h3><p>50 artes A4 para prevenção e cuidado com a saúde da mulher.</p><a href="kit-outubro-rosa.html">Ver o kit completo <span>↗</span></a></div></article><article class="campaign-card campaign-card--blue"><div class="campaign-art campaign-art--coming"><span>EM BREVE</span><strong>NOVEMBRO<br />AZUL</strong><i aria-hidden="true">✦</i></div><div class="campaign-content"><span class="campaign-month">PRÓXIMO LANÇAMENTO</span><h3>Novembro Azul</h3><p>Materiais para conscientização e prevenção da saúde do homem.</p><span class="campaign-soon">Em breve</span></div></article></div><div class="campaign-cta"><div><strong>Encontre o kit ideal para sua campanha.</strong><span>Veja a prévia, os detalhes e as opções de cada coleção.</span></div><a class="button button--primary" href="kit-outubro-rosa.html">Conhecer Kit Outubro Rosa <span>↗</span></a></div></div>`;
  document.querySelector('.digital-hero').after(section);
  const septemberLink = section.querySelector('.campaign-card--yellow a');
  if (septemberLink) { septemberLink.href = 'kit-setembro-amarelo.html'; septemberLink.textContent = 'Ver detalhes do kit ↗'; septemberLink.removeAttribute('target'); }
  const octoberCard = section.querySelector('.campaign-card--pink');
  if (octoberCard) { const octoberLink = octoberCard.querySelector('a'); if (octoberLink) { octoberLink.href = 'kit-outubro-rosa.html'; octoberLink.textContent = 'Ver detalhes do kit ↗'; } }
}

if (document.querySelector('.products-grid')) {
  const style = document.createElement('style'); style.textContent = '.kit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:55px}.kit-card{padding:28px;background:var(--surface);border:1px solid var(--line);border-radius:8px}.kit-card--featured{background:linear-gradient(145deg,#114b65,#0d2338);border-color:rgba(24,231,244,.4)}.kit-index{color:var(--cyan);font-size:10px;letter-spacing:2px}.kit-card h3{font-size:24px;margin:30px 0 10px}.kit-card p{color:var(--muted);font-size:13px;min-height:42px;margin:0 0 18px}.kit-card a{color:var(--cyan);font-size:11px;font-weight:700;text-decoration:none}@media(max-width:800px){.kit-grid{grid-template-columns:1fr}}'; document.head.appendChild(style);
  const filters = document.querySelector('.filter-list');
  [['energia','Energia'],['automacao','Automação'],['gamer','Gamer e home office'],['servicos','Serviços']].forEach(([value,label]) => { const button=document.createElement('button'); button.className='filter-btn'; button.dataset.filter=value; button.textContent=label; filters.appendChild(button); });
  const wa='https://wa.me/5592991587858?text=';
  [['energia','⌁','Nobreaks e proteção','Proteja computadores, roteadores, CFTV e equipamentos contra quedas e oscilações de energia.','Nobreaks|Filtros de linha|Baterias','Consultar opções','Quero consultar nobreaks e proteção de energia.'],['automacao','▤','Automação comercial','Equipamentos para lojas, mercados, farmácias e pequenos negócios: PDV, impressão e controle.','Leitor de código|Impressora térmica','Montar solução','Quero uma solução de automação comercial.'],['gamer','✦','Gamer e home office','Monitores, placas de vídeo, periféricos, webcams e acessórios para jogar ou trabalhar melhor.','PCs gamers|Monitores|Headsets','Montar meu setup','Quero montar um setup gamer ou home office.'],['servicos','&lt;/&gt;','Serviços técnicos','Montagem, instalação de SSD e memória, formatação, migração de dados, configuração e manutenção.','Residencial|Empresarial','Solicitar atendimento','Quero solicitar um serviço técnico.']].forEach(([category,symbol,title,description,meta,action,message]) => { const card=document.createElement('article'); card.className='product-card'; card.dataset.category=category; card.innerHTML=`<div class="product-visual"><span class="product-symbol">${symbol}</span></div><h3>${title}</h3><p>${description}</p><div class="product-meta">${meta.split('|').map(item=>`<span>${item}</span>`).join('')}</div><a class="product-cta" href="${wa}${encodeURIComponent(message)}" target="_blank" rel="noopener">${action} ↗</a>`; document.querySelector('.products-grid').appendChild(card); });
  const kits=document.createElement('div'); kits.className='kit-grid'; kits.innerHTML=[['KIT 01','Home Office','Computador, monitor, teclado, mouse, webcam e nobreak.','Kit Home Office'],['KIT 02','Empresa','Computadores, impressora, rede, nobreak e suporte técnico.','Kit Empresa'],['KIT 03','Segurança','Câmeras, gravador, HD, cabos e instalação de CFTV.','Kit Segurança']].map(([index,title,text,message],i)=>`<article class="kit-card ${i===1?'kit-card--featured':''}"><span class="kit-index">${index}</span><h3>${title}</h3><p>${text}</p><a href="${wa}${encodeURIComponent('Quero montar um '+message+'.')}" target="_blank" rel="noopener">Montar kit ↗</a></article>`).join(''); document.querySelector('.complete-kit').before(kits);
  document.querySelectorAll('.filter-btn').forEach(button=>button.addEventListener('click',()=>{ document.querySelectorAll('.filter-btn').forEach(item=>item.classList.remove('is-active')); button.classList.add('is-active'); const filter=button.dataset.filter; document.querySelectorAll('.product-card').forEach(card=>card.classList.toggle('is-hidden',filter!=='todos'&&card.dataset.category!==filter)); }));
}

if (document.querySelector('.digital-hero') && !document.querySelector('.campaign-section')) {
  const checkoutUrl = 'https://pay.kiwify.com.br/ey4EZjF';
  const campaignSection = document.createElement('section');
  campaignSection.className = 'campaign-section section-pad';
  campaignSection.innerHTML = `<div class="container"><div class="section-heading"><div><p class="eyebrow">Kits prontos para suas campanhas</p><h2>Comunicação que <span>gera conexão.</span></h2></div><p>Kits de imagens para empresas, lojas, profissionais e redes sociais. Escolha a campanha e comece a divulgar.</p></div><div class="campaign-grid"><article class="campaign-card campaign-card--yellow"><span class="campaign-month">SETEMBRO</span><h3>Setembro Amarelo</h3><p>Conteúdos de conscientização e valorização da vida.</p><a href="${checkoutUrl}" target="_blank" rel="noopener">Comprar kit <span>↗</span></a></article><article class="campaign-card campaign-card--pink"><span class="campaign-month">OUTUBRO</span><h3>Outubro Rosa</h3><p>Artes para prevenção e cuidado com a saúde da mulher.</p><a href="${checkoutUrl}" target="_blank" rel="noopener">Comprar kit <span>↗</span></a></article><article class="campaign-card campaign-card--blue"><span class="campaign-month">NOVEMBRO</span><h3>Novembro Azul</h3><p>Materiais para conscientização e prevenção da saúde do homem.</p><a href="${checkoutUrl}" target="_blank" rel="noopener">Comprar kit <span>↗</span></a></article></div><div class="campaign-cta"><div><strong>Todos os kits em um só lugar.</strong><span>Tenha acesso às campanhas e atualize sua comunicação durante o ano.</span></div><a class="button button--primary" href="${checkoutUrl}" target="_blank" rel="noopener">Comprar agora <span>↗</span></a></div></div>`;
  document.querySelector('.digital-hero').after(campaignSection);
  const campaignLinks = campaignSection.querySelectorAll('.campaign-card a');
  campaignLinks.forEach((link, index) => { if (index > 0) { link.removeAttribute('href'); link.removeAttribute('target'); link.removeAttribute('rel'); link.textContent = 'Link em breve'; link.style.opacity = '0.65'; } });
  const campaignCta = campaignSection.querySelector('.campaign-cta');
  if (campaignCta) { campaignCta.querySelector('strong').textContent = 'Comece pelo Setembro Amarelo.'; campaignCta.querySelector('span').textContent = 'Os próximos kits terão seus próprios links de checkout.'; campaignCta.querySelector('.button').innerHTML = 'Comprar kit Setembro Amarelo <span>↗</span>'; }
  const campaignStyle = document.createElement('style');
  campaignStyle.textContent = '.campaign-section{padding-top:50px;background:rgba(13,31,53,.28)}.campaign-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.campaign-card{min-height:220px;padding:28px;border-radius:9px;border:1px solid var(--line);display:flex;flex-direction:column;justify-content:flex-end;position:relative;overflow:hidden}.campaign-card:before{content:"";position:absolute;width:180px;height:180px;border:1px solid currentColor;border-radius:50%;right:-65px;top:-65px;opacity:.35}.campaign-card--yellow{color:#ffe27a;background:linear-gradient(145deg,#51471b,#172238)}.campaign-card--pink{color:#ff93b7;background:linear-gradient(145deg,#51223c,#172238)}.campaign-card--blue{color:#70b9ff;background:linear-gradient(145deg,#193b67,#172238)}.campaign-month{font-size:10px;letter-spacing:2px;font-weight:700;margin-bottom:auto}.campaign-card h3{font-size:23px;color:var(--text);margin:35px 0 8px}.campaign-card p{color:#b6c7d9;font-size:13px;margin:0 0 18px}.campaign-card a{color:currentColor;font-size:11px;font-weight:700;text-decoration:none}.campaign-card a span{font-size:16px;margin-left:5px}.campaign-cta{margin-top:18px;padding:22px 28px;border:1px solid rgba(24,231,244,.35);border-radius:8px;background:#0b1e32;display:flex;align-items:center;justify-content:space-between;gap:24px}.campaign-cta strong{display:block;color:var(--text);font-family:"Space Grotesk",sans-serif;font-size:20px}.campaign-cta span{color:var(--muted);display:block;font-size:13px;margin-top:4px}@media(max-width:800px){.campaign-grid{grid-template-columns:1fr}.campaign-cta{display:block}.campaign-cta .button{margin-top:20px}}';
  document.head.appendChild(campaignStyle);
}
